apiVersion: apps/v1
kind: Deployment
metadata:
  name: nik-backend-deploy
  labels:
    app: nik-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nik-backend
  template:
    metadata:
      labels:
        app: nik-backend
    spec:
      containers:
      - name: nik-backend-pod
        image: docker0411/backend-app:v2
        env:
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "nikpsdb"
          - name: DB_HOST
            value: "10.103.136.104"
          - name: PORT
            value: "4000"
        ports:
        - containerPort: 4000
