apiVersion: apps/v1
kind: Deployment
metadata:
  name: nik-appdemo-deploy
  labels:
    app: nik-appdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nik-appdemo-psdb
  template:
    metadata:
      labels:
        app: nik-appdemo-psdb
    spec:
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
      - name: nik-appdemo-pod
        image: postgres:alpine
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-persistent-storage
